language: android
jdk: oraclejdk8
android:
components:
- tools
- platform-tools
# The BuildTools version used by your project
- build-tools-25.0.2

# The SDK version used to compile your project
- android-25
- extra-google-m2repository
- extra-android-m2repository
licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'
before_install:
- chmod +x gradlew