language: android
jdk: oraclejdk8
android:
components:

# The BuildTools version used by your project
- build-tools-25.0.2

# The SDK version used to compile your project
- android-25

before_install:
- chmod +x gradlew